### ISSUE TITLE
This library will support to react native or not ?

### ISSUE THREAD

**Issue by Babygalla123** [st-one-io/node-open-protocol#19]
Hi... 
Thanks for the great library . i had tried this in node js. 
It is working fine.
But my main intention is i want to use this library in react native. since i am developing mobile application in react native.
I could able to add the library to react native project using ''npm'', and i am able to see in  'package.json' file  under dependencies.

"dependencies": {
    "node-open-protocol": "^1.1.1",
    "react": "16.11.0",
    "react-native": "0.62.2"} 

late, when i run my code i am getting error like library not found. Could you please help on this.

Thanks in advance!!

**Comment by gfcittolin** [comment]
Hey, we have no experience here, with react native, and since we use node.js specific APIs to open TCP sockets, there may be the need to do something else in order to be able to do it from a react native context.
Do you know something about it? If you'd provide some code that would support it, we could happily integrate in the current library!

**Comment by gfcittolin** [comment]
A 5 second search led me to [react-native-tcp-socket](https://www.npmjs.com/package/react-native-tcp-socket), that might do the job you want. If you test it and need to change anything here, just open a PR for it! :)

**Comment by Babygalla123** [comment]
Hi.. gfcirrolin ,
Thanks for your quick reply. 
actually my intention is, i want to communicate with atlas copco st wrench tool. 
I found this link in google for communicating with it and and send parameters to tool using node js. the same one i want to implement through react native. 
This library will help me to do or not ?
If yes , please provide the steps for it.
If no, is there any other alternative for it .

Thanks in Advance !!

**Comment by gfcittolin** [comment]
This library has been developed solely with Node.JS in mind, so using it outside of this environment is neither tested nor supported by the current code base. Maybe I could help out if I knew anything about React, but unfortunately I don't, nor we have the available time to invest in porting it. This library can be your starting point talking to ST-Wrench from react, but from here on you're on your own.

That said, if you have any question or issue regarding the library, feel free to open an issue! If you want to contribute back any changes you may need to do, they're always welcome.

**Comment by gfcittolin** [comment]
This issue is being closed for now
